### ISSUE TITLE
But may be chernikovka is THE most

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#1]
We should provide here evidence/arguments till we close this issue.

**Comment by SashaKenny** [comment]
Это предложение нужно корректировать?

**Comment by GataullinRR** [comment]
Нужно найти правило, по поводу использования артикля здесь. Кажется, что тут нужен the.

**Comment by SashaKenny** [comment]
Most без артикля обычно используется в функции прилагательного, и переводится как "большинство", "большая часть".

Например:
They ate most of the cake.
Они съели большую часть пирога.

Most days I go for a jog.
В большинство дней я совершаю пробежки.

Most также может использоваться в функции превосходной степени, и ставится перед наречиями.

Например:
He objected to the results of the election most strongly.
Он очень сильно возражал против результатов выборов.

The Most обычно используется в функции превосходной степени, и ставится перед прилагательными, состоящими из двух и более слогов (см. степени сравнения прилагательных).

Например:
The Miss World competition is held every year to find the most beautiful woman in the world.
Конкурс "Мисс Мира" проводится каждый год, чтобы выбрать самую красивую женщину в мире.

**Comment by SashaKenny** [comment]
Тут точно нужен THE)
