### ISSUE TITLE
there is <ARE> so many funny stickers

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#10]

**Comment by GataullinRR** [comment]
![image](https://user-images.githubusercontent.com/34606364/44307204-93464a00-a3b7-11e8-92ad-956dabce9c40.png)

**Comment by SashaKenny** [comment]
Тут без сомнений there are)
Примеры:
There are two books on the shelf. Там есть две книги на полке. 
There are a few problems. Там есть несколько проблем.
