### ISSUE TITLE
I liked <HAVE LIKED> to skip

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#12]

**Comment by SashaKenny** [comment]
Я думаю здесь Past Simple, поскольку это действие завершилось еще в прошлом и связи с настоящим уже не имеет)...вроде.  Иногда тяжело понять по смыслу какое время применить, но если сомневаюсь применяю Simple

**Comment by GataullinRR** [comment]
Да и правда наверное разницы нет. Просто слышал, что PP употребляется в случаях, когда речь идет о жизненном опыте.

**Comment by SashaKenny** [comment]
Дааа PP используют, когда про жизненный опыт. и теперь я совсем запуталась. Думаю можно и так и так сказать, но возможно предложения будут иметь немного разный смысл)
