### ISSUE TITLE
because be <BEEING> a programmer in 21 century it’s <IS> really cool

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#15]

**Comment by SashaKenny** [comment]
I totally agree)) my terrible mistakes(

**Comment by GataullinRR** [comment]
А вот гугл не согласен. Он BEEING в данном контексте переводит как БУДУЧИ, а не быть. Скорее всего он не прав, но лучше спрошу в школе.

**Comment by SashaKenny** [comment]
Гугл трансейт часто бывает не прав, но из-за него я тоже начала сомневаться теперь

**Comment by GataullinRR** [comment]
**because BEEING a programmer in 21 century IS really cool**
