### ISSUE TITLE
I <HAVE> never understand  <UNDERSTOOD> people who ...

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#18]

**Comment by SashaKenny** [comment]
No comment))))

**Comment by GataullinRR** [comment]
Нужна помощь, потому что можно сказать:
**I do not understand**

**Comment by GataullinRR** [comment]
Думаю, здесь нет разницы между:
I HAVE never UNDERSTOOD people who ... 
и
I never understood people who ...

Нашел такие цитаты:
I **never understood** people who don't have bookshelves.
― George Plimpton
“I **have never understood** why people who can swallow the enormous improbability of a personal God boggle at a personal Devil.”
― Graham Greene
