### ISSUE TITLE
The chernikovka or chernikovka?

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#4]

**Comment by SashaKenny** [comment]
Артикль the с географическими названиями
Определенный артикль употребляется с географическими названиями, которые обозначают:

1. Стороны света (cardinal points):
the North / the north – Север (как территориальное обозначение) / север (как направление);
the South / the south – Юг (как территориальное обозначение) / юг (как направление);
the East / the east – Восток (как территориальное обозначение) / восток (как направление);
the West / the west – Запад (как территориальное обозначение) / запад (как направление).
2. Полюса, полушария (poles, hemispheres):
the North Pole – Северный полюс;
the South Pole – Южный полюс;
the Western Hemisphere / the western hemisphere – Западное полушарие (как территориальное обозначение) / западное полушарие (как направление);
the Eastern Hemisphere / the eastern hemisphere – Восточное полушарие (как территориальное обозначение) / восточное полушарие (как направление);
the Northern Hemisphere / the northern hemisphere – Северное полушарие (как территориальное обозначение) / северное полушарие (как направление);
the Southern Hemisphere / the southern hemisphere – Южное полушарие (как территориальное обозначение) / южное полушарие (как направление).
3. Регионы (regions):
the Far East – Дальний Восток;
the north of Canada – север Канады;
the Middle East – Ближний Восток;
the Highlands – Северо-Шотландское нагорье;
the south of England – юг Англии;
the Caucasus – Кавказ.
4. Страны (countries), названия которых представляют собой существительные во множественном числе:
the Philippines – Филиппины;
the Netherlands – Нидерланды;
the United States of America – США;
the United Arab Emirates – Объединенные Арабские Эмираты;
the Baltic States – Прибалтика.
5. Страны, в названии которых есть слова kingdom (королевство), republic (республика), federation (федерация):
the United Kingdom of Great Britain and Northern Ireland – Объединенное Королевство Великобритании и Северной Ирландии;
the Kingdom of Denmark – Королевство Дании;
the Republic of Cuba – Республика Куба;
the German Federal Republic – Федеративная Республика Германии;
the Russian Federation – Российская Федерация;
the Czech Republic – Чешская Республика;
the People’s Republic of China – Китайская Народная Республика.
Если же называть страну без слов «республика», «королевство», «федерация», то артикль не нужен:

Germany – Германия;
Denmark – Дания;
Russia – Россия.
6. Океаны (oceans), проливы (straits), моря (seas), реки (rivers), каналы (canals/channels), течения (currents):
the Atlantic Ocean – Атлантический океан;
the Pacific Ocean – Тихий океан;
the Indian Ocean – Индийский океан;
the Black Sea – Черное море;
the Dead Sea – Мертвое море;
the Red Sea – Красное море;
the Thames – Темза;
the Volga – Волга;
the Don – Дон;
the Suez Canal – Суэцкий канал;
the Strait of Magellan – Магелланов пролив;
the Bosporus – пролив Босфор;
the Bering Strait – Берингов пролив;
the English Channel – Ла-Манш;
the Panama Canal – Панамский канал;
the Strait of Dover – Дуврский пролив / Па-де-Кале;
the Strait of Gibraltar – Гибралтарский пролив;
the Amazon – Амазонка;
the Nile – Нил;
the Gulf Stream – течение Гольфстрим;
the Sea of Japan – Японское море.
7. Полуострова (peninsulas), мысы (capes):
the Indochinese Peninsula – полуостров Индокитай;
the Balkan Peninsula – Балканский полуостров;
the Iberian Peninsula – Пиренейский полуостров;
the Cape of Good Hope – мыс Доброй Надежды.
Здесь есть несколько исключений:

Cape Horn – мыс Горн;
Cape Chelyuskin – мыс Челюскин.
8. Группы озер (groups of lakes):
the Great Lakes – Великие озера;
the Seliger – Селигер.
Обратите внимание: если рядом с названием озера используется слово lake, то определенный артикль не нужен:

Lake Baikal – озеро Байкал;
Lake Ontario – озеро Онтарио;
Lake Geneva – Женевское озеро.
9. Группы островов (groups of islands):
the Virgin Islands – Виргинские острова;
the Canary Islands (the Canaries) – Канарские острова (Канары);
the British Isles – Британские острова;
the Bahamas – Багамы;
the Azores – Азорские острова;
the Falkland Islands – Фолклендские острова.
10.Горные массивы (chains of mountains), холмы (hills):
the Black Hills – Черные холмы;
the Apennines – Апеннины;
the Rocky Mountains – Скалистые горы;
the Andes – Анды;
the Urals – Уральские горы;
the Alps – Альпы;
the Margalla Hills – холмы Маргалла;
the Seven Hills of Rome – семь холмов Рима;
the Chocolate Hills – Шоколадные холмы;
the Himalayas – Гималаи.
11. Равнины (plains), долины (valleys), пустыни (deserts):
the Great Plains – плато Великие равнины;
the Willamette Valley – долина Уилламетт;
the Jezreel Valley – Изреельская долина;
the Mississippi Valley – долина Миссисипи;
the Sahara Desert – пустыня Сахара;
the Karakum Desert (the Kara Kum, the Kara-Kum) – Каракумы, пустыня Каракумы;
the Kalahari Desert – Калахари;
the Arabian Desert – пустыни Аравийского полуострова.
Обратите внимание: с названиями многих долин артикль не используется.  Мы рекомендуем всегда проверять такие имена собственные в словаре, чтобы не ошибиться, например:

Death Valley – Долина Смерти;
Yosemite Valley – долина Йосемити;
Monument Valley – Долина монументов.
Заливы (gulfs/bays). Если в названии залива есть предлог of, то мы ставим артикль the, если предлога нет, артикль не нужен:
the Gulf of Mexico – Мексиканский залив;
the Gulf of Finland – Финский залив;
the Gulf of Aden – Аденский залив;
the Bay of Bengal – Бенгальский залив.
Hudson Bay – Гудзонский залив;
San Francisco Bay – залив Сан-Франциско.

**Comment by SashaKenny** [comment]
Я думаю точно Chernikovka, потому что the только перед именами собственными из списка.
