### ISSUE TITLE
Have you never been in <TO> chernikovka?

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#5]

**Comment by SashaKenny** [comment]
![7d73f5da-c640-442d-8ecf-a3fea407c93a](https://user-images.githubusercontent.com/42510105/44307299-73178a80-a3b9-11e8-99d8-c1a4b3bd1f29.png)
![0f44dc5f-e119-4b0a-97c0-3d459b003fe9](https://user-images.githubusercontent.com/42510105/44307300-73178a80-a3b9-11e8-8a2e-f9ea2a3359ee.png)

**Comment by SashaKenny** [comment]
Ты прав, тут точно TO
