### ISSUE TITLE
I think so many <A LOT OF>? alcoholics and addicts live there

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#6]

**Comment by SashaKenny** [comment]
![a5a89914-7c68-4f44-a920-9599aaf6e598](https://user-images.githubusercontent.com/42510105/44307221-fc2dc200-a3b7-11e8-9661-598a63de661d.png)
![b56fa981-1e61-4e86-aef4-a8770d8321c0](https://user-images.githubusercontent.com/42510105/44307222-fc2dc200-a3b7-11e8-93d5-106b3091a590.png)
![3ca1e9bc-8fd4-455c-9b82-54d90b7f449c](https://user-images.githubusercontent.com/42510105/44307223-fcc65880-a3b7-11e8-81d3-c052b3090a76.png)

**Comment by SashaKenny** [comment]
Many можно если с исчисляемыми и является частью подлежащего, я так поняла. Не понимаю, почему нам на курсах это все объясняют как строгое правило((

**Comment by GataullinRR** [comment]
Нам говорили, что many и much употребляются только с отрицательными и вопросительными предложениями. Поэтому я и подумал, что может быть будет лучше заменить на a lot of.

**Comment by GataullinRR** [comment]
I think so many SO MANY alcoholics and addicts live there.
