### ISSUE TITLE
it is also kinda a crime <KINDA CRIME> to let <LETTING>? live people <PEOPLE LIVE>? with incurable diseases

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#7]

**Comment by GataullinRR** [comment]
1 и 2 Думаю здесь стоит полагаться на интуицию и опыт. Сложно найти правило, которое разложило бы все по полкам. Хотя KINDA CRIME лучше подходит (ИМХО).
3 Тут явно должно быть let PEOPLE LIVE. Ошибся с порядком слов

**it is also KINDA CRIME to let PEOPLE LIVE with incurable diseases.**

**Comment by SashaKenny** [comment]
Kinda crime лучше звучит и смотрится))
