### ISSUE TITLE
Some countries practice <ARE PRACTICING>? euthanasia

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#8]

**Comment by SashaKenny** [comment]
<img width="833" alt="2018-08-19 23 29 35" src="https://user-images.githubusercontent.com/42510105/44311826-db8d5880-a407-11e8-9a84-ce7e1b8b01f5.png">

**Comment by SashaKenny** [comment]
Думаю тут подойдет Pr Simple, practicing это наверное когда практикуют в данный момент, а страны в общем практикуют.
