### ISSUE TITLE
we got caught OR <WAS CAUGHT>

### ISSUE THREAD

**Issue by GataullinRR** [GataullinRR/English#9]

**Comment by SashaKenny** [comment]
<img width="871" alt="2018-08-19 22 37 33" src="https://user-images.githubusercontent.com/42510105/44311589-7e8fa380-a403-11e8-9928-7473019204fe.png">
<img width="818" alt="2018-08-19 22 41 53" src="https://user-images.githubusercontent.com/42510105/44311590-7e8fa380-a403-11e8-9836-5f346061ce7c.png">

**Comment by SashaKenny** [comment]
Мне кажется здесь оба варианта подойдут, и они оба Simple Past.

**Comment by GataullinRR** [comment]
Погуглил. Видимо большой разницы нет, разве что got более неформальная форма.
